#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  packer build -var iso_dir="$shome" --only=vmware-iso osx.json
}

source sub "$BASH_SOURCE" "$@"
