#!/usr/bin/env bash

function _basebox_osx_profile {
  local shome="${_basebox_osx_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$shome/osx-bin:$PATH"
}

_basebox_osx_profile
