#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:/Applications/VMware Fusion.app/Contents/Library:$PATH"
}

profile "$@"
